server:
  port: 8202

spring:
  application:
    name: service-item
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.128

feign:
  client:
    config:
      default:
        connectTimeout: 600000
        readTimeout: 600000